### ISSUE TITLE
Exception with rapid PowerShell SecureString entry

### ISSUE THREAD

**Issue by crossan007** [Microsoft/console#27]
Linked from: https://github.com/PowerShell/PowerShell/issues/3511

I'm seeing an issue on Windows 10 1703 where typing too quickly into a ```Read-Host -AsSecureString``` prompt will forcefully terminate the running script.  

For example: typing "asdf;lkjasdf;lkjasdf;lkjasd" very rapidly succession will cause the script to terminate.

The exception is not presented to the PowerShell terminal user; however it is stored in the ```$StackTrace``` variable:
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

```

![image](https://user-images.githubusercontent.com/11679900/29820393-4eab61ce-8c92-11e7-9388-54d1ff689e65.png)

**Comment by zadjii-msft** [comment]
As @SteveL-msft mentioned in the other thread, this seems to have been fixed as of Insiders build 10.0.16278. Could you try out that build?

I don't remember fixing this, though April was a long time ago. If we were pinged about this on April 13th, then the fix definitely isn't in 15063.

I can't get it to repro locally on my 16270 build, so I'm gonna guess this is already fixed.

**Comment by Nacimota** [comment]
I have also reproduced this in 15063, but it works as expected in 16275, so I suspect @zadjii-msft is right and it was indeed fixed in RS3.

**Comment by HansKindberg** [comment]
Same issue in Windows 10 Version 1703 (OS-version 15063.726)

**Comment by bitcrazed** [comment]
Unable to repro on recent builds. Looks like this is fixed.

**Comment by martinzwirner** [comment]
At least in PowerShell 7.2.1 on Windows 10 Version 10.0.18363 this is not solved IMO.

Running ``Read-Host -AsSecureString`` and using Ctrl+V pastes one star and doesn't return the correct value.

Issue does not appear when using right click, and it does not appear when using PowerShell 7.2.1 inside Windows Terminal or Jetbrains Rider.

**Comment by DHowett** [comment]
Oh, this makes sense now!

PowerShell usually handles <kbd>Ctrl+V</kbd> itself, by reading the clipboard and inserting its contents at the cursor. When you run `Read-Host`, it _still receives the raw <kbd>Ctrl+V</kbd>_. However, since it's reading input, it does _not_ parse it.

Evidence:

1. <kbd>Ctrl+V</kbd> is a single character (`U+0016 SYNCHRONOUS IDLE`)
2. `[console]::readkey()` reports that it is <kbd>Ctrl+V</kbd>

```
% [console]::readkey()
▬
KeyChar Key Modifiers
------- --- ---------
      ▬   V   Control
```

**Comment by martinzwirner** [comment]
@DHowett This could well be the explanation. But anyway it's a suprising behavior for the user, especially as `Ctrl-V` works when entering commands. So it would be nice to see this changed.
