### ISSUE TITLE
Windows 1809: Shift + Space no longer produces a space on the console

### ISSUE THREAD

**Issue by lithium112** [Microsoft/console#282]
Windows Build Number: Microsoft Windows [Version 10.0.17763.1]

Pressing the space bar while holding down the shift key no longer types a space on the console. This is inconsistent with prior versions of the console and most other text input fields. I've noticed this especially when typing out PowerShell commands that contain pipes or single-character aliased cmdlets.

For example, if I intend to type: 

`Get-Process | % Id
`

when typing fast and holding the shift key down throughout the entire ' | % ' sequence, the end result is: 

`Get-Process|%Id
`

Which is an invalid command.

**Comment by DHowett-MSFT** [comment]
This is a (known) regression in PSReadline, lzybkr/PSReadLine#719, which was updated in 1809. That regression was fixed with lzybkr/PSReadline@3229956a1973ffe65c24dbbe9ba421e62bcbf0b3. Unfortunately, the console team doesn't control the speed at which PSReadline is ingested into the OS.

@SteveL-MSFT may know more.

There's a clever workaround that you can insert into your PowerShell profile to work around it in the meantime.

```powershell
# Work around an RS5/PSReadline-2.0.0+beta2 bug (Spacebar is not marked Vital)
Set-PSReadlineKeyHandler "Shift+SpaceBar" -ScriptBlock {
        [Microsoft.Powershell.PSConsoleReadLine]::Insert(' ')
}
```

**Comment by lithium112** [comment]
Great, thanks for the very fast response.

**Comment by thw0rted** [comment]
This is still happening on 1909.   @SteveL-MSFT did the fix not wind up in the "next release" as planned?  I'm on Microsoft branded hardware (Surface Book 2) with no available Windows updates showing.

(If it's not in the current release, and the terminal team doesn't control when the PSReadLine package gets updated, who does control that?)

**Comment by akhan3** [comment]
This bug is also affecting Windows 10 Pro version 2004 (build 19041.388). This issue should be reopened.

**Comment by DHowett** [comment]
I am not reopening a bug that's doesn't represent something my team can fix. If you have a grievance, please move it to [the PowerShell repository](https://github.com/powershell/powershell).
